# conda environment for dbbact-calour
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f doc_conda_environment.yml

name: dbbact-calour

channels:
- conda-forge
- defaults

dependencies:
- python=3.4*
- pip=9.0*
- nose
- pep8
- flake8
- numpy
- scipy
- pyqt>=5
- pandas
- matplotlib
- h5py
- scikit-learn
- statsmodels
- ipywidgets
- sphinx
- sphinx_bootstrap_theme
- pip:
    - coveralls
    - sphinx-autodoc-typehints
    - docrep
    - nbsphinx
    - scikit-bio>=0.5.1
    - biom-format
